### ISSUE TITLE
about angr management

### ISSUE THREAD

**Issue by pegah1371** [angr/angr-management#10] opened 2016-07-05 09:55 UTC
![question](https://cloud.githubusercontent.com/assets/20297776/16580947/368e8060-42bc-11e6-804e-e92055e504c1.PNG)
 documents about angr management is not strong . i run my own c program in angr management and i see this cfg on it, my question is what does this CFG show ?! what does it mean?!
ok, if i want to run in without angr management what should i do step by step? what is linux terminal cmd to run it?!!

Thank you for your help.

**Comment by ltfish** [comment] 2016-07-05 17:54
There was something wrong with refreshing the CFG view. It should be fixed in the latest version (both on PyPI and on GitHub). Update your angr-management and see if the issue is resolved.

**Comment by pegah1371** [comment] 2016-07-05 21:31
![question2](https://cloud.githubusercontent.com/assets/20297776/16600550/db5b4eb0-431c-11e6-828b-c4286b495c95.PNG)
is it the last version??
i just want to know for example what does(" sub_0x400390 : " ) that was in cfg in last pic means just this!!!!!!!! and other number

**Comment by ltfish** [comment] 2016-07-05 21:33
The version number in your picture is the version of your Jupyter QtConsole and IPython, not angr-management. angr-management does not show version number explicitly anywhere on the main window. I would suggest you simply checkout the latest code from this repo and run it.

**Comment by pegah1371** [comment] 2016-07-05 22:00
i cant upgrade i have exception!! 
i dont know why you dont answer me 
i just want to know what does your node in cfg means??
is intermediate code.
just a little explain what the cfg which drawn by angr managemetn means
jus this no thing more

**Comment by ltfish** [comment] 2016-07-05 22:02
Man, like I said, the graph you saw, as posted in your first post, is corrupted. That was caused by a known bug in early versions of angr-management, and is fixed now. The only way for you to get a working and meaningful graph is to update your angr-management. This is what I explained before. Is it clear enough?

**Comment by ltfish** [comment] 2016-07-05 22:03
> i cant upgrade i have exception!! 

What is the exception you are seeing?

**Comment by pegah1371** [comment] 2016-07-05 22:14
Thank you for taking this into consideration

![questio3](https://cloud.githubusercontent.com/assets/20297776/16601690/8944fa7a-4323-11e6-87eb-4e45bb873043.PNG)

**Comment by pegah1371** [comment] 2016-07-05 22:19
i just open terminal and run pip install angr-management --upgrade!

**Comment by pegah1371** [comment] 2016-07-05 22:27
sorry, but i am new in angr and linux too.
toy said " checkout the latest code from this repo and run it. " how i do that?!

**Comment by ltfish** [comment] 2016-07-05 22:39
You need permission to write files to `/usr/local/lib/`. Please run `sudo pip install angr-management --upgrade`.

**Comment by pegah1371** [comment] 2016-07-06 03:38
i do data and saw this pic
![question4](https://cloud.githubusercontent.com/assets/20297776/16606848/baaac18a-4350-11e6-9a23-a9db652f0f41.PNG)

but when run angr managament again the cfg was like old one.
what should i do know?

**Comment by ltfish** [comment] 2016-07-06 03:55
Hi, can you please post another screenshot of angr-management, so that I know you are using the new version?

**Comment by rhelmot** [comment] 2016-07-06 04:23
Hi! I noticed a problem in the screenshot you posted - fish told you to install with `sudo` because he thought you were trying to install angr-management outside a virtual environment, but I can see the `workon angr` line in your newest screenshot, so you clearly are trying to use a virtualenv. 

You need to be inside your virtualenv before you run the install command. I can see that you've used the `workon angr` command before - this activates your virtualenv. You can tell if you're inside your virtualenv because of the `(angr)` before your command line prompt.

Basically, run this:

```
workon angr
pip install angr-management --upgrade
```

As an additional note, I'm worried about your motivations for using angr. In general, angr is a very technical tool, not suited for beginners to binary analysis. For example, your question about the meaning of "sub_0x400390" makes us (the angr team) a little wary about holding your hand through this whole process - the answer to that question is "it's the subroutine at address 0x400390, which is technically not part of the main binary, but an address in angr's externs object, which provides addresses for unresolved imported symbols." If this answer goes entirely over your head, you may want to reconsider using angr...

**Comment by pegah1371** [comment] 2016-07-07 19:54
i am very appriciate for your answers i run your command and i see this  angr 
![question3](https://cloud.githubusercontent.com/assets/20297776/16667446/c3199966-44a1-11e6-85f4-7a127176ea6e.PNG)
 the problem is when i run angr management an error occur and i am so sad about it please guide me i need your helps and i dont have enough time.this is screen shot after run command
![question5](https://cloud.githubusercontent.com/assets/20297776/16667543/4019370a-44a2-11e6-85da-467ccb1cdb54.PNG)

**Comment by pegah1371** [comment] 2016-07-07 20:28
and sorry what does angr backward slicing means?
![question6](https://cloud.githubusercontent.com/assets/20297776/16668621/0233313e-44a7-11e6-867f-76cb737657f6.PNG)

**Comment by zardus** [comment] 2016-07-07 22:56
Here is some reading material about backwards slicing:
https://en.m.wikipedia.org/wiki/Program_slicing

Regarding the other exception, can you try reinstalling grandalf? It might
fix the issue.

and sorry what does angr backward slicing means?
[image: question6]
<https://cloud.githubusercontent.com/assets/20297776/16668621/0233313e-44a7-11e6-867f-76cb737657f6.PNG>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angr/angr-management/issues/10#issuecomment-231197246>,
or mute the thread
<https://github.com/notifications/unsubscribe/ADSzlwuV8F_-7Pw1NzXr8-lNVtwtuGwPks5qTWFVgaJpZM4JE9DS>
.

**Comment by pegah1371** [comment] 2016-07-08 09:10
dear sir
of course , i know what is backward slicing i just want to know hear what does that mean in bytcode.in pic that i sent print bs : .... 
but thanks for your answer

**Comment by pegah1371** [comment] 2016-07-08 09:13
" can you try reinstalling grandalf? It might fix the issue. " how can i do it??

**Comment by rhelmot** [comment] 2016-07-08 09:17
```
pip install -I grandalf
```

The `-I` flag means "ignore any existing installation"

**Comment by pegah1371** [comment] 2016-07-08 09:30
I would appreciate a reply at your earliest convenience thank you so much .
i run this command and i see angr management know, but other error occur whaen i click on cfg buttom in angr management and i can not see cfg in angr management
![q1](https://cloud.githubusercontent.com/assets/20297776/16683286/3eda93c6-4514-11e6-8e87-3419d61fce99.PNG)
![q2](https://cloud.githubusercontent.com/assets/20297776/16683285/3ea645f8-4514-11e6-97b8-2f3f090e671b.PNG)
what should i do know?? please help me again
best wishes

**Comment by rhelmot** [comment] 2016-07-08 09:45
This is correct. Please click on one of the functions in the sidebar to view its control flow graph.

**Comment by pegah1371** [comment] 2016-07-08 10:07
but it does not look like cfg  , it is just node and does not shown the links between nodes?

**Comment by rhelmot** [comment] 2016-07-08 10:09
It is only the CFG for a single function. Try more functions, some of them should be more complex. The ones starting with `plt.` are PLT stubs and are necessarily only a single block.

**Closed** 2016-09-14 07:48 UTC
