### ISSUE TITLE
Angr management ImportError/AttributeError

### ISSUE THREAD

**Issue by TSarre** [angr/angr-management#16] opened 2016-12-04 13:54 UTC
I installed angr management using
`pip install angr-management`
like described in the readme. Then when trying to start it, I get the following output:

```
root@kali:~# python -m angrmanagement
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 27, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 11, in main
    from ui.main import Main
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
    exec code in mod.__dict__
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/main.enaml", line 22, in 
    from .state import RegistersItem, MemoryItem
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
    exec code in mod.__dict__
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/state.enaml", line 8, in 
    from ..widgets.api import Table
ImportError: No module named widgets.api
```

After cloning and running the same command in the `angr-mangement` folder I'm getting a different error:
```
root@kali:~/Desktop/angr-management# python -m angrmanagement
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/Desktop/angr-management/angrmanagement/__main__.py", line 26, in <module>
    main()
  File "/root/Desktop/angr-management/angrmanagement/__main__.py", line 11, in main
    from ui.main import Main
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
    exec code in mod.__dict__
  File "angrmanagement/ui/main.enaml", line 21, in 
    from .state import RegistersItem, MemoryItem
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
    exec code in mod.__dict__
  File "angrmanagement/ui/state.enaml", line 8, in 
    from ..widgets.api import Table
  File "angrmanagement/widgets/api.py", line 3, in <module>
    from .flowgraph import FlowGraph
  File "angrmanagement/widgets/flowgraph.py", line 17, in <module>
    class FlowGraph(Frame):
  File "angrmanagement/widgets/flowgraph.py", line 23, in FlowGraph
    disasm = d_(Typed(angr.analyses.Disassembly))
AttributeError: 'module' object has no attribute 'Disassembly'
```

**Comment by zardus** [comment] 2016-12-07 07:40
It looks like you're not running the very latest version of angr (and all subcomponents). Can you try upgrading them (`pip install -U angr`) and see if that helps?

**Comment by TSarre** [comment] 2016-12-07 10:23
It didn't help. Here is the Terminal output:
```
root@kali:~# pip install -U angr
Collecting angr
  Downloading angr-5.6.12.3.tar.gz (268kB)
    100% |████████████████████████████████| 276kB 876kB/s 
Requirement already up-to-date: capstone in /usr/lib/python2.7/dist-packages (from angr)
Requirement already up-to-date: networkx in /usr/local/lib/python2.7/dist-packages (from angr)
Requirement already up-to-date: futures in /usr/lib/python2.7/dist-packages (from angr)
Requirement already up-to-date: progressbar in /usr/local/lib/python2.7/dist-packages (from angr)
Requirement already up-to-date: mulpyplexer in /usr/local/lib/python2.7/dist-packages (from angr)
Requirement already up-to-date: cooldict in /usr/local/lib/python2.7/dist-packages (from angr)
Requirement already up-to-date: ana in /usr/local/lib/python2.7/dist-packages (from angr)
Collecting archinfo>=5.6.12.3 (from angr)
  Downloading archinfo-5.6.12.3.tar.gz
Collecting pyvex>=5.6.12.3 (from angr)
  Downloading pyvex-5.6.12.3.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 1.8MB/s 
Collecting claripy>=5.6.12.3 (from angr)
  Downloading claripy-5.6.12.3.tar.gz (95kB)
    100% |████████████████████████████████| 102kB 1.3MB/s 
Collecting simuvex>=5.6.12.3 (from angr)
  Downloading simuvex-5.6.12.3.tar.gz (169kB)
    100% |████████████████████████████████| 174kB 1.3MB/s 
Collecting cle>=5.6.12.3 (from angr)
  Downloading cle-5.6.12.3.tar.gz (41kB)
    100% |████████████████████████████████| 51kB 2.0MB/s 
Requirement already up-to-date: cachetools in /usr/local/lib/python2.7/dist-packages (from angr)
Collecting decorator>=3.4.0 (from networkx->angr)
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Requirement already up-to-date: pyelftools in /usr/local/lib/python2.7/dist-packages (from archinfo>=5.6.12.3->angr)
Collecting pycparser (from pyvex>=5.6.12.3->angr)
Collecting cffi>=1.0.3 (from pyvex>=5.6.12.3->angr)
  Using cached cffi-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already up-to-date: angr-only-z3-custom==9002 in /usr/local/lib/python2.7/dist-packages (from claripy>=5.6.12.3->angr)
Requirement already up-to-date: bintrees in /usr/local/lib/python2.7/dist-packages (from simuvex>=5.6.12.3->angr)
Requirement already up-to-date: dpkt-fix in /usr/local/lib/python2.7/dist-packages (from simuvex>=5.6.12.3->angr)
Requirement already up-to-date: idalink in /usr/local/lib/python2.7/dist-packages (from cle>=5.6.12.3->angr)
Requirement already up-to-date: pefile in /usr/lib/python2.7/dist-packages (from cle>=5.6.12.3->angr)
Collecting z3-solver (from angr-only-z3-custom==9002->claripy>=5.6.12.3->angr)
Requirement already up-to-date: rpyc in /usr/local/lib/python2.7/dist-packages (from idalink->cle>=5.6.12.3->angr)
Requirement already up-to-date: plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc->idalink->cle>=5.6.12.3->angr)
Building wheels for collected packages: angr, archinfo, pyvex, claripy, simuvex, cle
  Running setup.py bdist_wheel for angr ... done
  Stored in directory: /root/.cache/pip/wheels/7a/f4/c6/69df19173b964e971a00c174d17c4c75c358d89ac1686ad0dc
  Running setup.py bdist_wheel for archinfo ... done
  Stored in directory: /root/.cache/pip/wheels/47/63/c3/73c86111d852033fa9489c9c3e4bcbdd88704472956eb66398
  Running setup.py bdist_wheel for pyvex ... done
  Stored in directory: /root/.cache/pip/wheels/18/fd/80/93133fe4165f6bec33ab8e1cdf30d83d0ff6593e08808dffec
  Running setup.py bdist_wheel for claripy ... done
  Stored in directory: /root/.cache/pip/wheels/17/1c/c1/15b5f922ca385ee1a96bc89f4885c74a3e22b52e19e4a20a73
  Running setup.py bdist_wheel for simuvex ... done
  Stored in directory: /root/.cache/pip/wheels/70/95/67/c5b4c061febd189d119eee4d723d4cb148438e2770dc7d6c76
  Running setup.py bdist_wheel for cle ... done
  Stored in directory: /root/.cache/pip/wheels/c4/e8/22/f1eb34c44ef206f3c089a280394dfbabe4f970e34cc4030765
Successfully built angr archinfo pyvex claripy simuvex cle
Installing collected packages: archinfo, pycparser, cffi, pyvex, claripy, simuvex, cle, angr, decorator, z3-solver
  Found existing installation: archinfo 5.6.10.5
    Uninstalling archinfo-5.6.10.5:
      Successfully uninstalled archinfo-5.6.10.5
  Found existing installation: pycparser 2.16
    Uninstalling pycparser-2.16:
      Successfully uninstalled pycparser-2.16
  Found existing installation: cffi 1.8.3
    Uninstalling cffi-1.8.3:
      Successfully uninstalled cffi-1.8.3
  Found existing installation: pyvex 5.6.10.5
    Uninstalling pyvex-5.6.10.5:
      Successfully uninstalled pyvex-5.6.10.5
  Found existing installation: claripy 5.6.10.12
    Uninstalling claripy-5.6.10.12:
      Successfully uninstalled claripy-5.6.10.12
  Found existing installation: simuvex 5.6.10.12
    Uninstalling simuvex-5.6.10.12:
      Successfully uninstalled simuvex-5.6.10.12
  Found existing installation: cle 5.6.10.5
    Uninstalling cle-5.6.10.5:
      Successfully uninstalled cle-5.6.10.5
  Found existing installation: angr 5.6.10.12
    Uninstalling angr-5.6.10.12:
      Successfully uninstalled angr-5.6.10.12
  Found existing installation: decorator 4.0.6
    Uninstalling decorator-4.0.6:
      Successfully uninstalled decorator-4.0.6
  Found existing installation: z3-solver 4.4.2.1.post1
    Uninstalling z3-solver-4.4.2.1.post1:
      Successfully uninstalled z3-solver-4.4.2.1.post1
Successfully installed angr-5.6.12.3 archinfo-5.6.12.3 cffi-1.9.1 claripy-5.6.12.3 cle-5.6.12.3 decorator-4.0.10 pycparser-2.17 pyvex-5.6.12.3 simuvex-5.6.12.3 z3-solver-4.5.1.0
root@kali:~# pip install angr-management
Requirement already satisfied: angr-management in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: enaml==0.9.8 in /usr/local/lib/python2.7/dist-packages (from angr-management)
Requirement already satisfied: angr in /usr/local/lib/python2.7/dist-packages (from angr-management)
Requirement already satisfied: pygments in /usr/lib/python2.7/dist-packages (from angr-management)
Requirement already satisfied: websocket-client in /usr/local/lib/python2.7/dist-packages (from angr-management)
Requirement already satisfied: atom>=0.3.8 in /usr/local/lib/python2.7/dist-packages (from enaml==0.9.8->angr-management)
Requirement already satisfied: ply>=3.4 in /usr/lib/python2.7/dist-packages (from enaml==0.9.8->angr-management)
Requirement already satisfied: distribute in /usr/local/lib/python2.7/dist-packages (from enaml==0.9.8->angr-management)
Requirement already satisfied: kiwisolver>=0.1.2 in /usr/local/lib/python2.7/dist-packages (from enaml==0.9.8->angr-management)
Requirement already satisfied: futures in /usr/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: simuvex>=5.6.12.3 in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: capstone in /usr/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: mulpyplexer in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: cooldict in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: archinfo>=5.6.12.3 in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: claripy>=5.6.12.3 in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: ana in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: pyvex>=5.6.12.3 in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: networkx in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: cle>=5.6.12.3 in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: cachetools in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: progressbar in /usr/local/lib/python2.7/dist-packages (from angr->angr-management)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from websocket-client->angr-management)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python2.7/dist-packages (from distribute->enaml==0.9.8->angr-management)
Requirement already satisfied: dpkt-fix in /usr/local/lib/python2.7/dist-packages (from simuvex>=5.6.12.3->angr->angr-management)
Requirement already satisfied: bintrees in /usr/local/lib/python2.7/dist-packages (from simuvex>=5.6.12.3->angr->angr-management)
Requirement already satisfied: pyelftools in /usr/local/lib/python2.7/dist-packages (from archinfo>=5.6.12.3->angr->angr-management)
Requirement already satisfied: angr-only-z3-custom==9002 in /usr/local/lib/python2.7/dist-packages (from claripy>=5.6.12.3->angr->angr-management)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from pyvex>=5.6.12.3->angr->angr-management)
Requirement already satisfied: cffi>=1.0.3 in /usr/local/lib/python2.7/dist-packages (from pyvex>=5.6.12.3->angr->angr-management)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python2.7/dist-packages (from networkx->angr->angr-management)
Requirement already satisfied: idalink in /usr/local/lib/python2.7/dist-packages (from cle>=5.6.12.3->angr->angr-management)
Requirement already satisfied: pefile in /usr/lib/python2.7/dist-packages (from cle>=5.6.12.3->angr->angr-management)
Requirement already satisfied: z3-solver in /usr/local/lib/python2.7/dist-packages (from angr-only-z3-custom==9002->claripy>=5.6.12.3->angr->angr-management)
Requirement already satisfied: rpyc in /usr/local/lib/python2.7/dist-packages (from idalink->cle>=5.6.12.3->angr->angr-management)
Requirement already satisfied: plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc->idalink->cle>=5.6.12.3->angr->angr-management)
root@kali:~# python -m angrmanagement
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 27, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/__main__.py", line 11, in main
    from ui.main import Main
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
    exec code in mod.__dict__
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/main.enaml", line 22, in 
    from .state import RegistersItem, MemoryItem
  File "/usr/local/lib/python2.7/dist-packages/enaml/core/import_hooks.py", line 143, in load_module
    exec code in mod.__dict__
  File "/usr/local/lib/python2.7/dist-packages/angrmanagement/ui/state.enaml", line 8, in 
    from ..widgets.api import Table
ImportError: No module named widgets.api
```

**Comment by ltfish** [comment] 2016-12-07 18:03
It seems to be a distribution problem. Let me test it on a new Ubuntu install.

**Comment by rhelmot** [comment] 2016-12-19 00:49
Duplicate of #15 and should be resolved.

**Closed by rhelmot** 2016-12-19 00:49 UTC
